apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: reverseproxy
  name: reverseproxy
spec:
  ports:
    - name: "8180"
      port: 8180
      protocol: TCP
      targetPort: 8180
  selector:
    app: reverseproxy
  type: ClusterIP
status:
  loadBalancer: {}
